### ISSUE TITLE
没用，翻译成功之后打开还是英文

### ISSUE THREAD

**Issue by 2565911151** [zedoCN/VVM-Translator#1]
没用，翻译成功之后打开还是英文

**Comment by Cyccode** [comment]
有用，只是菜单没有翻译

**Comment by zedoCN** [comment]
目标平台是什么？什么版本的VisualVM？路径是否正确？  

可以参考一下演示视频（  
https://www.bilibili.com/video/BV1cm4y1g7p3/

**Comment by Cyccode** [comment]
我VisualVM是最新的2.1.9版，jdk12，可以翻译成功，就是菜单没有全部翻译出来，但完全不影响使用，感谢作者

**Comment by Cyccode** [comment]
我的VisualVM是最新的2.1.9版，jdk12，可以翻译成功，就是菜单没有全部翻译出来，但完全不影响使用，感谢作者
